openapi: 3.1.1
info:
  title: Core access-groups pubsub API
  description: Core services for Scalar
  version: 1.0.1
  contact:
    name: Marc from Scalar
    url: https://scalar.com
    email: support@scalar.com
security:
- BearerAuth: []
tags:
- name: pubsub
paths:
  /pubsub/sdk-build-complete:
    post:
      tags:
      - pubsub
      description: Side effect processing after SDK generation completes
      operationId: postpubsubSdkBuildComplete
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: 'null'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: No auth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '422':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
        '500':
          description: Uncaught error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                buildUid:
                  $ref: '#/components/schemas/nanoid'
                teamUid:
                  $ref: '#/components/schemas/nanoid'
                buildMessage:
                  type: string
                apiJsonSha:
                  type: string
                apiYamlSha:
                  type: string
              required:
              - buildUid
              - teamUid
              additionalProperties: false
        required: true
  /pubsub/sdk-build-failed:
    post:
      tags:
      - pubsub
      description: Side effect processing after SDK generation fails
      operationId: postpubsubSdkBuildFailed
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: 'null'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: No auth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '422':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
        '500':
          description: Uncaught error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                buildUid:
                  $ref: '#/components/schemas/nanoid'
                teamUid:
                  $ref: '#/components/schemas/nanoid'
                generationLog:
                  type: string
                buildMessage:
                  type: string
              required:
              - buildUid
              - teamUid
              additionalProperties: false
        required: true
  /pubsub/api-version-created/create-sdk-version:
    post:
      tags:
      - pubsub
      description: API version created SDK processing
      operationId: postpubsubApiVersionCreatedCreateSdkVersion
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: 'null'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: No auth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '422':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
        '500':
          description: Uncaught error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                teamUid:
                  $ref: '#/components/schemas/nanoid'
                version:
                  $ref: '#/components/schemas/version'
                versionUid:
                  $ref: '#/components/schemas/nanoid'
                apiUid:
                  $ref: '#/components/schemas/nanoid'
                namespace:
                  $ref: '#/components/schemas/namespace'
                slug:
                  $ref: '#/components/schemas/slug'
                isLatest:
                  type: boolean
                isPrivate:
                  type: boolean
                docsProjectUid:
                  $ref: '#/components/schemas/nanoid'
              required:
              - title
              - description
              - teamUid
              - version
              - versionUid
              - apiUid
              - namespace
              - slug
              - isLatest
              - isPrivate
              additionalProperties: false
        required: true
  /pubsub/sdk-version-created:
    post:
      tags:
      - pubsub
      description: PubSub SDK version created
      operationId: postpubsubSdkVersionCreated
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: 'null'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: No auth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '422':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
        '500':
          description: Uncaught error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sdk:
                  type: object
                  properties:
                    uid:
                      $ref: '#/components/schemas/nanoid'
                    namespace:
                      $ref: '#/components/schemas/namespace'
                    slug:
                      $ref: '#/components/schemas/slug'
                    version:
                      $ref: '#/components/schemas/version'
                  required:
                  - uid
                  - namespace
                  - slug
                  - version
                  additionalProperties: false
                api:
                  type: object
                  properties:
                    uid:
                      $ref: '#/components/schemas/nanoid'
                    namespace:
                      $ref: '#/components/schemas/namespace'
                    slug:
                      $ref: '#/components/schemas/slug'
                    version:
                      $ref: '#/components/schemas/version'
                    upgraded:
                      default: false
                      type: boolean
                  required:
                  - uid
                  - namespace
                  - slug
                  - version
                  - upgraded
                  additionalProperties: false
                config:
                  type: string
                repository:
                  type: string
                language:
                  type: string
                  enum:
                  - typescript
                  - python
                  - csharp
                  - java
                  - ruby
                  - php
                  - go
                autoBump:
                  type: boolean
                teamUid:
                  $ref: '#/components/schemas/nanoid'
              required:
              - sdk
              - api
              - config
              - language
              - teamUid
              additionalProperties: false
        required: true
  /pubsub/sdk-repository-linked:
    post:
      tags:
      - pubsub
      description: Handle side effects for SDK repository linking
      operationId: postpubsubSdkRepositoryLinked
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: 'null'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: No auth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '422':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
        '500':
          description: Uncaught error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sdkUid:
                  $ref: '#/components/schemas/nanoid'
                teamUid:
                  $ref: '#/components/schemas/nanoid'
              required:
              - sdkUid
              - teamUid
              additionalProperties: false
        required: true
  /pubsub/sdk-git-complete:
    post:
      tags:
      - pubsub
      description: Side effect processing after SDK git sync succeeds
      operationId: postpubsubSdkGitComplete
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: 'null'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: No auth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '422':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
        '500':
          description: Uncaught error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                buildUid:
                  $ref: '#/components/schemas/nanoid'
                teamUid:
                  $ref: '#/components/schemas/nanoid'
                repository:
                  type: string
                pullRequest:
                  type: number
                commitHash:
                  type: string
                gitMessage:
                  type: string
              required:
              - buildUid
              - teamUid
              - repository
              - pullRequest
              - commitHash
              additionalProperties: false
        required: true
  /pubsub/sdk-git-failed:
    post:
      tags:
      - pubsub
      description: Side effect processing after SDK git sync fails
      operationId: postpubsubSdkGitFailed
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: 'null'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
        '401':
          description: No auth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        '422':
          description: Invalid payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
        '500':
          description: Uncaught error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                buildUid:
                  $ref: '#/components/schemas/nanoid'
                teamUid:
                  $ref: '#/components/schemas/nanoid'
                gitMessage:
                  type: string
              required:
              - buildUid
              - teamUid
              - gitMessage
              additionalProperties: false
        required: true
components:
  schemas:
    namespace:
      type: string
      minLength: 3
      maxLength: 50
      pattern: ^[a-zA-Z0-9-_]+$
    nanoid:
      type: string
      minLength: 5
    '404':
      type: object
      properties:
        message:
          type: string
        code:
          type: string
      required:
      - message
      - code
    '401':
      type: object
      properties:
        message:
          type: string
        code:
          type: string
      required:
      - message
      - code
    slug:
      type: string
      minLength: 3
      maxLength: 60
      pattern: ^[a-z](?:[a-z0-9-]*[a-z0-9])?$
    version:
      type: string
      minLength: 1
    '500':
      type: object
      properties:
        message:
          type: string
        code:
          type: string
      required:
      - message
      - code
    '400':
      type: object
      properties:
        message:
          type: string
        code:
          type: string
      required:
      - message
      - code
    '403':
      type: object
      properties:
        message:
          type: string
        code:
          type: string
      required:
      - message
      - code
    '422':
      type: object
      properties:
        message:
          type: string
        code:
          type: string
      required:
      - message
      - code
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
